export default Doctors = [
  {
    id: 'DOC001',
    doctorName: 'Dr. Randeep Guleria',
    specialization: 'Pulmonologist',
    hospital: 'AIIMS Delhi',
    city: 'Delhi',
    hospitalPhone: '011-26588500',
    image:
      'https://imgs.search.brave.com/z8UTDMGE93t7pczZfgxTvIxK8cg0V2-6-yaepPOm3Dg/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9nZXR3/ZWxsZ28uY29tL3Vw/bG9hZHMvRHIuJTIw/UmFuZGVlcCUyMEd1/bGVyaWEuanBlZw',
    profileUrl: 'https://www.aiims.edu',
    dataSource: 'Wikipedia & AIIMS Official',
  },
  {
    id: 'DOC002',
    doctorName: 'Dr. Sudeep Gupta',
    specialization: 'Medical Oncologist',
    hospital: 'Tata Memorial Centre',
    city: 'Mumbai',
    hospitalPhone: '022-24177000',
    image:
      'https://imgs.search.brave.com/5CYioItL0RtIjbvyFgLBqw5XMwAQgZIGqzDxGFXNkjo/rs:fit:200:200:1:0/g:ce/aHR0cHM6Ly9jbGlu/aWNzb25jYWxsLmNv/bS93cC1jb250ZW50/L3VwbG9hZHMvMjAy/MS8wNC9kci4tc3Vk/ZWVwLWd1cHRhLmpw/Zw',
    profileUrl: 'https://tmc.gov.in',
    dataSource: 'Wikipedia & Tata Memorial Official',
  },
  {
    id: 'DOC003',
    doctorName: 'Dr. Arvind Kumar',
    specialization: 'Thoracic Surgeon',
    hospital: 'Medanta – The Medicity',
    city: 'Gurgaon',
    hospitalPhone: '0124-4141414',
    image:
      'https://content.jdmagicbox.com/comp/gurgaon/l3/011pxx11.xx11.230511184420.b9l3/catalogue/dr-arvind-kumar-medanta-the-medicity-gurgaon-sector-38-gurgaon-oncologist-surgeon-doctors-6yo5ca95fo.jpg',
    profileUrl: 'https://www.medanta.org',
    dataSource: 'Wikipedia',
  },
  {
    id: 'DOC004',
    doctorName: 'Dr. Ashok Vaid',
    specialization: 'Medical Oncologist',
    hospital: 'Medanta – The Medicity',
    city: 'Gurgaon',
    hospitalPhone: '0124-4141414',
    image:
      'https://medanta.s3.ap-south-1.amazonaws.com/doctors/November2024/xN21pZIEwk6WwF9vv11Msr33VnPHHo-metaRHIgQXNob2sgVmFpZC5wbmc=-.png',
    profileUrl: 'https://www.medanta.org',
    dataSource: 'Medanta Official',
  },
  {
    id: 'DOC005',
    doctorName: 'Dr. Imran Khan',
    specialization: 'Medical Oncologist',
    hospital: 'Fortis Escorts Heart Institute',
    city: 'New Delhi',
    hospitalPhone: '011-41654000',
    image:
      'https://www.fortishealthcare.com/drupal-data/styles/doctor_image/azblob/doctors/dr-imran-khan-11707.jpg?itok=20GpSLcP',
    profileUrl: 'https://www.fortishealthcare.com',
    dataSource: 'Fortis Official',
  },
  {
    id: 'DOC006',
    doctorName: 'Dr. Ankur Bahl',
    specialization: 'Medical Oncologist',
    hospital: 'Fortis Memorial Research Institute',
    city: 'Gurgaon',
    hospitalPhone: '0124-4141414',
    image:
      'https://www.fortishealthcare.com/drupal-data/styles/doctor_image/azblob/doctors/dr-ankur-bahl-6587.png?itok=6SBAwvQ8',
    profileUrl: 'https://www.fortishealthcare.com',
    dataSource: 'Fortis Official',
  },
  {
    id: 'DOC007',
    doctorName: 'Dr. Nitesh Rohatgi',
    specialization: 'Medical Oncologist',
    hospital: 'Fortis Memorial Research Institute',
    city: 'Gurgaon',
    hospitalPhone: '0124-4141414',
    image:
      'https://www.fortishealthcare.com/drupal-data/styles/doctor_image/azblob/doctors/dr-nitesh-rohatgi-6621.jpg?itok=zraznEpm',
    profileUrl: 'https://www.fortishealthcare.com',
    dataSource: 'Fortis Official',
  },
  {
    id: 'DOC008',
    doctorName: 'Dr. Namita Sood',
    specialization: 'Pulmonologist',
    hospital: 'Max Super Speciality Hospital',
    city: 'Delhi',
    hospitalPhone: '011-26515050',
    image:
      'https://imgs.search.brave.com/yDKvxuS-2Ylcuzm8Gq_QACrylw-__cCjGa-hCPjVcfE/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9kb3hp/bWl0eS1yZXMuY2xv/dWRpbmFyeS5jb20v/aW1hZ2VzL2ZfYXV0/byxxX2F1dG8sdF9w/dWJsaWNfcHJvZmls/ZV9waG90b18zMjB4/MzIwL3ltcjJqeHM1/OG50ZmNnZ2p6NGN3/L25hbWl0YS1zb29k/LW1kLXNhY3JhbWVu/dG8tY2EuanBn',
    profileUrl: 'https://www.maxhealthcare.in',
    dataSource: 'Max Healthcare Official',
  },
  {
    id: 'DOC009',
    doctorName: 'Dr. Naveen Kumar Ailawadi',
    specialization: 'Pulmonologist',
    hospital: 'Max Super Speciality Hospital',
    city: 'Delhi',
    hospitalPhone: '011-26515050',
    image:
      'https://imgs.search.brave.com/DC3CXbvdL6E2KiHIBEcy-xIvG2clPkq4DGIQvk1Gguk/rs:fit:200:200:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMxLWZhYnJpYy5w/cmFjdG8uY29tL2Rv/Y3Rvci80Mjc2Njcv/ZHItbmF2ZWVuLWt1/bWFyLWFpbGF3YWRp/LTVkMzE1OTMxMjE3/NzQucG5n',
    profileUrl: 'https://www.maxhealthcare.in',
    dataSource: 'Max Healthcare Official',
  },
  {
    id: 'DOC010',
    doctorName: 'Dr. Ashwini Budrukkar',
    specialization: 'Medical Oncologist',
    hospital: 'Apollo Hospitals Chennai',
    city: 'Chennai',
    hospitalPhone: '044-28293333',
    image:
      'https://imgs.search.brave.com/cJAh61WHuAq4jqRzvrUp_50TSmA_FqYAH4uf-nW3cig/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9kcnVw/YWwtY2RuLWhmYWVk/ZGNkYm5nNWhmYmcu/YTAxLmF6dXJlZmQu/bmV0L3NpdGVzL2Rl/ZmF1bHQvZmlsZXMv/c3R5bGVzL2RvY3Rv/cl9jYXJkL3B1Ymxp/Yy8yMDI1LTAxL2Ry/LXJhamEtcmFtYW4t/c3VyZ2ljYWwtb25j/b2xvZ3ktaW4tY2hl/bm5haS5wbmcud2Vi/cD9pdG9rPTNUN2Nr/M1c2',
    profileUrl: 'https://www.apollohospitals.com',
    dataSource: 'Apollo Hospitals Public Listing',
  },
  {
    id: 'DOC011',
    doctorName: 'Dr. Narasimhan R',
    specialization: 'Pulmonologist',
    hospital: 'Apollo Hospitals Chennai',
    city: 'Chennai',
    hospitalPhone: '044-28293333',
    image:
      'https://imgs.search.brave.com/rjICf2IpnYRZGgGPQ2SaPJPMRyu5xK9IKtrx2gIL1io/rs:fit:200:200:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuYXBvbGxvMjQ3/LmluL2RvY3RvcnMv/YmU4ODE4MWEtNzE2/Ny00OTE2LTlhNWMt/OTQzNWIxM2U2OTAy/LTE3MDQzMDExMjgw/NTEucG5n',
    profileUrl: 'https://www.apollohospitals.com',
    dataSource: 'Apollo Hospitals Public Listing',
  },
  {
    id: 'DOC012',
    doctorName: 'Dr. Samir Sahu',
    specialization: 'Pulmonologist',
    hospital: 'Apollo Hospitals Bhubaneswar',
    city: 'Bhubaneswar',
    hospitalPhone: '0674-3983333',
    image:
      'https://imgs.search.brave.com/l8sjwFY2rHraf8yWa7b9d2gudeT8cNpA35punNvtLGc/rs:fit:200:200:1:0/g:ce/aHR0cHM6Ly93d3cu/bG9naW50b2hlYWx0/aC5jb20vYXNzZXRz/L3VwbG9hZHMvZG9j/dG9ycy8xYzdjZmRl/NjlmYTUwNTNiZjQz/YWY5MjMzMTY3ODFh/MC5qcGc',
    profileUrl: 'https://www.apollohospitals.com',
    dataSource: 'Apollo Hospitals Public Listing',
  },
  {
    id: 'DOC013',
    doctorName: 'Dr. Subramanyeswar Rao',
    specialization: 'Surgical Oncologist',
    hospital: 'Apollo Hospitals Hyderabad',
    city: 'Hyderabad',
    hospitalPhone: '040-23450000',
    image:
      'https://imgs.search.brave.com/5pv7UbTfltqb-7ZGxA_GY0r6N0DKgfNe_gBwWpeHoDs/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9iYXNh/dmF0YXJha2FtLm9y/Zy93cC1jb250ZW50/L3VwbG9hZHMvMjAy/MS8xMC9CRVNULVNV/UkdJQ0FMLU9OQ09M/T0dJU1QtSU4tSU5E/SUEtRFItVC1TVUJS/QU1BTllFU1dBUi1S/QU8tNjAweDYwMC5q/cGc',
    profileUrl: 'https://www.apollohospitals.com',
    dataSource: 'Apollo Hospitals Public Listing',
  },
  // {
  //   id: 'DOC014',
  //   doctorName: 'Dr. Raj B Singh',
  //   specialization: 'Pulmonologist',
  //   hospital: 'Apollo Hospitals Chennai',
  //   city: 'Chennai',
  //   hospitalPhone: '044-28293333',
  //   image: 'https://randomuser.me/api/portraits/men/63.jpg',
  //   profileUrl: 'https://www.apollohospitals.com',
  //   dataSource: 'Apollo Hospitals Public Listing',
  // },
  // {
  //   id: 'DOC015',
  //   doctorName: 'Dr. A R Gayathri Devi',
  //   specialization: 'Pulmonologist',
  //   hospital: 'Apollo Hospitals Chennai',
  //   city: 'Chennai',
  //   hospitalPhone: '044-28293333',
  //   image: 'https://randomuser.me/api/portraits/women/61.jpg',
  //   profileUrl: 'https://www.apollohospitals.com',
  //   dataSource: 'Apollo Hospitals Public Listing',
  // },
  // {
  //   id: 'DOC016',
  //   doctorName: 'Dr. Prashant Chhajed',
  //   specialization: 'Pulmonologist',
  //   hospital: 'Fortis Hospital',
  //   city: 'Mumbai',
  //   hospitalPhone: '022-67994444',
  //   image: null,
  //   profileUrl: 'https://www.fortishealthcare.com',
  //   dataSource: 'Fortis Official',
  // },
  // {
  //   id: 'DOC017',
  //   doctorName: 'Dr. Shalini Khanna',
  //   specialization: 'Pulmonologist',
  //   hospital: 'Manipal Hospital',
  //   city: 'Bengaluru',
  //   hospitalPhone: '080-22221111',
  //   image: null,
  //   profileUrl: 'https://www.manipalhospitals.com',
  //   dataSource: 'Manipal Hospital Official',
  // },
  // {
  //   id: 'DOC018',
  //   doctorName: 'Dr. Harish Sharma',
  //   specialization: 'Pulmonologist',
  //   hospital: 'Narayana Health',
  //   city: 'Bengaluru',
  //   hospitalPhone: '080-71222222',
  //   image: null,
  //   profileUrl: 'https://www.narayanahealth.org',
  //   dataSource: 'Narayana Health Official',
  // },
  // {
  //   id: 'DOC019',
  //   doctorName: 'Dr. Neha Reddy',
  //   specialization: 'Respiratory Specialist',
  //   hospital: 'Narayana Health',
  //   city: 'Hyderabad',
  //   hospitalPhone: '080-71222222',
  //   image: null,
  //   profileUrl: 'https://www.narayanahealth.org',
  //   dataSource: 'Narayana Health Official',
  // },
  // {
  //   id: 'DOC020',
  //   doctorName: 'Dr. Pooja Mehta',
  //   specialization: 'Pulmonologist',
  //   hospital: 'Max Super Speciality Hospital',
  //   city: 'Mumbai',
  //   hospitalPhone: '022-26515050',
  //   image: null,
  //   profileUrl: 'https://www.maxhealthcare.in',
  //   dataSource: 'Max Healthcare Official',
  // },
];
